### ISSUE TITLE
not working react 16.0

### ISSUE THREAD

**Issue by pavelnikitin** [johanneshilden/impromptu-react-animated-header#2]

**Comment by pavelnikitin** [comment]
There is impromptu-animated-header.js.jsx in your folder error and else not working in react 16.0  with "impromptu-animated-header.jsx:35 Uncaught TypeError: this.refs.anchor.getDOMNode is not a function"
